name: Node.js CI

on:
  push:
    branches: [ master ]
   
  pull_request:
    branches: [ master ]
   
defaults:
  run:
    shell: bash
    working-directory: ts
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        git clone --depth 1 -b feature/aone-83973983-websocket https://github.com/aliyun/tea-typescript.git /tmp/tea-typescript
        cd /tmp/tea-typescript && npm install && npm run build
        cd $GITHUB_WORKSPACE/ts
        npm pkg set dependencies.@darabonba/typescript="file:/tmp/tea-typescript"
        npm install
    - run: npm run test-cov
    - uses: codecov/codecov-action@v4
      with:
        flags: typescript # optional
        token: ${{ secrets.CODECOV_TOKEN }}
